challan_bkp/challan/challan/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('challan/',include('traffic.urls'))
]

challan_bkp/challan/traffic/urls.py
from django.urls import path
from . import views
app_name='traffic'
urlpatterns = [
    path('home/',views.home_view,name='home'),
    path('generate/',views.generate,name="generate"),
    path('admin_generate/',views.admin_generate,name="admin_generate"),
    path('challans/', views.view_challans, name='view_challans'),
    path('rules/',views.traffic_rules,name="rules"),
    path('most_violations/',views.ViolationsByLocationView,name='violation'),
    path('register/',views.register_page,name='register'),
    path('police_register/',views.police_register_page,name='police_register'),
    path('police_login/',views.police_login_view,name='police_login'),
    path('contact/',views.contact,name='contact'),
    path('faq/',views.faq,name='faq'),
    path('user_login/',views.user_login_view,name='user_login'),
    path('user_logout/', views.user_logout_view, name='user_logout'),
    path('police_logout/', views.police_logout_view, name='police_logout'),
    path('admin_logout_view/', views.admin_logout_view, name='admin_logout_view'),
    path('police_dashboard/', views.police_dashboard, name='police_dashboard'),
    path('police_dashboard_content/', views.police_dashboard_content, name='police_dashboard_content'),
    path('admin_dashboard_content/', views.admin_dashboard_content, name='admin_dashboard_content'),
    path('admin_panel/', views.admin_panel_view, name='admin_panel'),
    path('admin_login/',views.admin_login_view,name="admin_login"),
    path('pending_challan/',views.pending_challan,name="pending_challan"),
    path('report/',views.report,name="report"),
    path('report_list/',views.report_list,name="report_list"),
    path('admin_report_list/',views.admin_report_list,name="admin_report_list"),
    path('challan_cancellation/', views.display_challans, name='display_challans'),
    path('admin_challan_cancellation/', views.admin_display_challans, name='admin_display_challans'),
    path('challan_cancellation/delete/<int:challan_id>/', views.delete_challan, name='delete_challan'),
    path('admin_challan_cancellation/delete/<int:challan_id>/', views.admin_delete_challan, name='admin_delete_challan'),
    path('challan_cancellation/delete/confirm-delete/<int:challan_id>/', views.confirm_delete_challan, name='confirm_delete_challan'),
    path('admin_challan_cancellation/delete/confirm-delete/<int:challan_id>/', views.admin_confirm_delete_challan, name='admin_confirm_delete_challan'),
    path('report_list/delete/<int:report_id>/', views.delete_complaint, name='delete_complaint'),
    path('admin_report_list/delete/<int:report_id>/', views.admin_delete_complaint, name='admin_delete_complaint'),
    path('report_list/delete/confirm-delete/<int:report_id>/', views.confirm_delete_complaint, name='confirm_delete_complaint'),
    path('admin_report_list/delete/confirm-delete/<int:report_id>/', views.admin_confirm_delete_complaint, name='admin_confirm_delete_complaint'),
    path('all_users_view/', views.all_users_view, name='all_users_view'),
    path('pay_challans/', views.pay_challans, name='pay_challans'),
    
   
    
    

]

  

   

challan_bkp/challan/traffic/models.py
from django.db import models

# Create your models here.
from django.db import models
from datetime import datetime,timedelta
from django.contrib.auth.models import User





def default_start_time():
    now = datetime.now()
    start = now.replace(hour=22, minute=0, second=0, microsecond=0)
    return start if start > now else start + timedelta(days=1)  

class Challan(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE,default=None)
   
    place_of_violation=models.CharField(max_length=100,default=None)
    date=models.DateField(default=datetime.now)
    time=models.TimeField(default=default_start_time)
    cat=(('Wrong Route','Wrong Route'),('Drunk and Drive','Drunk and Drive'),('No helmet','No helmet'),('Parked at No parking','Parked at No parking'),('Overspeed','Overspeed'),('Signal Jump','Signal Jump'))
    violation=models.CharField(max_length=50,choices=cat)
    fine_amount=models.DecimalField(max_digits=10000,decimal_places=2,default=None)


class Report(models.Model):
    registration_number=models.TextField(default=None)
    phone=models.IntegerField(default=None)
    compliant=models.TextField(default=None)








    

challan_bkp/challan/traffic/views.py
from django.shortcuts import render,  redirect,get_object_or_404
from .models import Challan, Report
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required,permission_required
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.db.models import Count
from django.contrib import messages
from django.db.models import Sum
import re
import razorpay


from django.contrib.auth.models import Group
from django.contrib.auth.models import User


def home_view(request):
    challans = Challan.objects.all()
    return render(request, 'traffic/home.html',{challans:"challans"})

def user_login_view(request):
    if request.method == 'POST':
        username_ = request.POST.get('vehicle_number', '')
        password_ = request.POST.get('password', '')
        print(username_)
        print(password_)
        
        user = authenticate(request,username=username_, password=password_)
        if user is not None :
            login(request, user)

            users = Group.objects.get(name='Users')
            
            if users in user.groups.all():
                
                return redirect('traffic:view_challans')
            
        messages.error(request, 'Invalid credentials. Please try again.')

    return render(request,'traffic/user_login.html' )

@login_required
def report(request):
    if request.method == 'POST':
        registration_number = request.POST.get('registration_number')
        phone = request.POST.get('phone')
        complaint = request.POST.get('complaint')


        report = Report(registration_number=registration_number, phone=phone, compliant=complaint)
        report.save()
        messages.success(request, 'Your complaint is registered')
       
        return render(request,'traffic/report.html')
    else:
        
        return render(request,'traffic/report.html')

def register_page(request):
    if request.method == 'GET':
        return render(request, 'traffic/register.html')
    elif request.method == 'POST':
        registration_number_ = request.POST.get('registration_number', '')
        name_ = request.POST.get('name', '')
        phone_ = request.POST.get('phone', '')
        password_ = request.POST.get('password', '')
        confirm_password = request.POST.get('confirm_password', '')

        if password_ == confirm_password:
            if registration_number_ == '':
                messages.error(request, 'Please enter your registration number')
                return redirect('traffic:register')
            elif name_ == '':
                messages.error(request, 'Please enter your name')
                return redirect('traffic:register')
            elif password_ == '':
                messages.error(request, 'Please enter your password')
                return redirect('traffic:register')
            elif confirm_password == '':
                messages.error(request, 'Please enter your confirm password')
                return redirect('traffic:register')
            elif phone_ == '':
                messages.error(request, 'Please enter your phone number')
                return redirect('traffic:register')

            elif User.objects.filter(username=registration_number_).exists():
                messages.error(request, 'Registration number already exists')
                return redirect('traffic:register')
            elif User.objects.filter(last_name=phone_).exists():
                messages.error(request, 'Phone number already exists')
                return redirect('traffic:register')
            elif len(phone_) != 10:
                messages.error(request, 'Phone number must contain ten digits')
                return redirect('traffic:register')
            elif not re.match(r'^[A-Z]{2}\d{2}[A-Z]{2}\d{4}$', registration_number_):
                messages.error(request, 'Registration number should be in the format "TS09FC2342"')
                return redirect('traffic:register')
            else:
                user = User.objects.create_user(username=registration_number_, password=password_)
                user.first_name = name_
                user.last_name = phone_
                user.save()
                user_group = Group.objects.get(name='Users')
                user.groups.add(user_group)
                context = {'msg': 'Registration Successful'}
                return render(request, 'traffic/error.html', context)
        else:
            messages.error(request, 'Make sure both passwords are the same')
            return redirect('traffic:register')

def contact(request):
    return render(request, 'traffic/contact_us.html') 

def traffic_rules(request):
    return render(request, "traffic/traffic_rules.html")

def user_logout_view(request):
    logout(request)
    return redirect('traffic:user_login')           

@login_required
def view_challans(request):
    user = request.user
    challans = Challan.objects.filter(user=user)
    return render(request, 'traffic/challan_view.html', {'challans': challans})

@login_required
def report_list(request):
    reports = Report.objects.all()
    return render(request, 'traffic/report_list.html', {'reports': reports})

@login_required
def police_dashboard(request):
     return render(request, 'traffic/police_dashboard.html')
@login_required
def police_dashboard_content(request):
    return render(request,'traffic/police_dashboard_content.html')

@login_required
def view_challans(request):
    user = request.user
    challans = Challan.objects.filter(user=user)

    if request.method == 'POST':
        challan_ids = request.POST.getlist('challan_ids')
        challans = Challan.objects.filter(id__in=challan_ids, user=user)
        total_amount = challans.aggregate(total=Sum('fine_amount'))['total']
        total_amount_paise = total_amount * 100
   
    

        return render(request, 'traffic/pay_challans.html', {'challans': challans, 'total_amount': total_amount, 'total_amount_paise': total_amount_paise})

    return render(request, 'traffic/challan_view.html', {'challans': challans})

@login_required
def generate(request):
    if request.method == 'POST':
       
        user_id = request.POST.get('user')
        user = User.objects.get(id=user_id)
        place_of_violation_ = request.POST.get('place_of_violation')
        date_ = request.POST.get('date')
        time_ = request.POST.get('time')
        violation_type = request.POST.get('violation_type')
        fine_amount_ = request.POST.get('fine_amount')

        try:
          

            challan = Challan(user=user,place_of_violation= place_of_violation_,date=date_ ,time=time_,violation=violation_type, fine_amount=fine_amount_)
            challan.save()
            

            messages.success(request, 'Challan Successfully Generated')
            return redirect('traffic:generate')
        except Challan.DoesNotExist:
            messages.error(request, 'Failed to generate challan')
            return redirect('traffic:generate')
        

    users = User.objects.filter(groups__name='Users')
    return render(request, "traffic/generate.html",{'users': users})

@login_required
def admin_generate(request):
    if request.method == 'POST':
       
        user_id = request.POST.get('user')
        user = User.objects.get(id=user_id)
        place_of_violation_ = request.POST.get('place_of_violation')
        date_ = request.POST.get('date')
        time_ = request.POST.get('time')
        violation_type = request.POST.get('violation_type')
        fine_amount_ = request.POST.get('fine_amount')

        try:
          

            challan = Challan(user=user,place_of_violation= place_of_violation_,date=date_ ,time=time_,violation=violation_type, fine_amount=fine_amount_)
            challan.save()
            

            messages.success(request, 'Challan Successfully Generated')
            return redirect('traffic:admin_generate')
        except Challan.DoesNotExist:
            messages.error(request, 'Failed to generate challan')
            return redirect('traffic:admin_generate')
        

    users = User.objects.filter(groups__name='Users')
    return render(request, "traffic/admin_generate.html",{'users': users})


@login_required
def pending_challan(request):
    challans = Challan.objects.all()
    return render(request, 'traffic/pending_challan.html', {'challans': challans})


def traffic_rules(request):
    return render(request, "traffic/traffic_rules.html")




@login_required
def admin_display_challans(request):
    challans = Challan.objects.all()
    return render(request, 'traffic/admin_challan_cancellation.html', {'challans': challans})

@login_required
def admin_confirm_delete_challan(request, challan_id):
    challan = get_object_or_404(Challan, id=challan_id)
    return render(request, 'traffic/admin_confirm_delete.html', {'challan': challan})



@login_required
def admin_confirm_delete_complaint(request, report_id):
    report = get_object_or_404(Report, id=report_id)
    return render(request, 'traffic/admin_confirm_delete_complaint.html', {'report': report})

@login_required
def admin_dashboard_content(request):
    return render(request,'traffic/admin_content.html')


def admin_login_view(request):
    if request.method == 'POST':
        username_ = request.POST.get('username', '')
        password_ = request.POST.get('password', '')
        user = authenticate(request, username=username_, password=password_)
        
        if user is not None and user.is_superuser :
            
            
            if user.groups.filter(name='Admin').exists():
                login(request, user)
                return redirect('traffic:admin_dashboard_content')
            
        messages.error(request, 'Invalid credentials. Please try again.')

    return render(request, 'traffic/admin_login.html')



@login_required
def admin_report_list(request):
    reports = Report.objects.all()

challan_bkp/challan/traffic/templates/traffic/admin_challan_cancellation.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
    body {
        font-family: Arial, sans-serif;
        background-color: #f2f2f2;
        margin: 0;
        padding: 20px;
    }
    
    h1 {
        text-align: center;
        margin-bottom: 20px;
    }
    
    table {
        width: 100%;
        border-collapse: collapse;
        margin-bottom: 20px;
    }
    
    th, td {
        padding: 10px;
        text-align: left;
        border-bottom: 1px solid #ddd;
    }
    
    th {
        background-color: #f5f5f5;
    }
    
    tr:hover {
        background-color: #f9f9f9;
    }
    
    .delete-button {
        text-decoration: none;
        background-color: #dc3545;
        color: white;
        padding: 5px 10px;
        border-radius: 3px;
    }
    
    .delete-button:hover {
        background-color: #c82333;
    }
</style>

</head>
<body>
 



    {% include 'traffic/police_dashboard_2.html' %}

    <form method="post" >
    {% csrf_token %}
    <table>
        <thead>
        <tr>
            <th>Name</th>
            <th>Place of Violation</th>
            <th>Date</th>
            <th>Time</th>
            <th>Violation</th>
            
        </tr>
        </thead>
        <tbody>
        {% for challan in challans %}
            <tr>
            <td>{{ challan.user.username }}</td>
            <td>{{ challan.place_of_violation }}</td>
            <td>{{ challan.date }}</td>
            <td>{{ challan.time }}</td>
            <td>{{ challan.violation }}</td>
            <td>
               
                
                <td><a href="{% url 'traffic:admin_confirm_delete_challan' challan.id %}" class="delete-button">Delete</a></td>
            </td>
            </tr>
        {% endfor %}
        </tbody>

    </table>
    </form>



        <form action="{% url 'traffic:admin_dashboard_content' %}">
            <button type="submit">Go to Home Page</button>
        </form>


   
</body>
</html>     

challan_bkp/challan/traffic/templates/traffic/admin_confirm_delete_complaint.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Confirm Delete Challan</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f2f2f2;
            margin: 0;
            padding: 20px;
        }
        
        h1 {
            text-align: center;
            margin-bottom: 20px;
        }
        
        .complaint-details {
            margin-bottom: 20px;
        }
        
        .button-container {
            text-align: center;
        }
        
        .confirm-button {
            background-color: #dc3545;
            color: white;
            padding: 5px 10px;
            border-radius: 3px;
            margin-right: 10px;
        }
        
        .cancel-button {
            background-color: #007bff;
            color: white;
            padding: 5px 10px;
            border-radius: 3px;
        }
    </style>
</head>
<body>

    
    <h1>Confirm Delete Complaint</h1>
 
    <div class="complaint-details">
        <h3>Are you sure you want to delete the following Complaint?</h3>
        <p>Registration Number: {{ report.registration_number }}</p>
        <p>Phone: {{ report.phone }}</p>
        <p>Complaint:{{ report.compliant }}</p>
        
    
    <div class="button-container">
        <a href="{% url 'traffic:admin_delete_complaint' report.id %}" class="confirm-button">Delete</a>
        <a href="{% url 'traffic:admin_report_list' %}" class="cancel-button">Cancel</a>
    </div>
</body>
</html>

challan_bkp/challan/traffic/templates/traffic/error.html
{% include 'traffic/navbar.html' %}

{% block content %}
<h5 style="margin:50px;">
    <center>
        {{msg}}
    </center>
</h5>
{% endblock content %}

challan_bkp/challan/traffic/templates/traffic/police_dashboard_2.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  {% load static %}
 
 

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  <style>
    
    body {
      font-family: Arial, sans-serif;
      background-color:#f8f9fa;
      margin: 0;
      padding: 0;
    }

    .header {
      background-color: #333;
      color: #fff;
      padding: 20px;
      text-align: center;
      box-shadow: 0 2px 10px rgba(0, 0, 0, 0.3);
    }

    .header h1 {
      margin: 0;
      font-size: 32px;
      text-transform: uppercase;
      letter-spacing: 2px;
    }

    .header img {
      max-width: 200px;
      margin-top: 10px;
    }

    h3 {
      text-align: center;
      margin-top: 30px;
      color: #333;
    }

    .navbar {
      background-color: #fff;
      padding: 10px;
      text-align: center;
      margin-bottom: 20px;
      box-shadow: 0 4px 10px rgba(0, 0, 0, 0.2);
    }

    .navbar a {
      color: #333;
      text-decoration: none;
      margin: 0 10px;
      font-weight: bold;
      transition: color 0.3s ease;
    }

    .navbar a:hover {
      color: #ff6b6b;
    }
    
  </style>
</head>
  <body>
    {% load static %}
  <div class="header">
  <h1>Telangana Traffic Police</h1>
  
  
</div>
<h3>E Challan Portal</h3>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
   
    <img src="{% static 'traffic/photos/2.png'%}" alt="Logo" style="height: 100px;">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="http://127.0.0.1:8000/challan/home">Home <span class="sr-only">(current)</span></a>

        <li class="nav-item active">
          <a class="nav-link" href="http://127.0.0.1:8000/challan/contact">Contact US</a> <span class="sr-only">(current)</span></a>

        <li class="nav-item active">
          <a class="nav-link" href="http://127.0.0.1:8000/challan/police_login">Police Login</a> <span class="sr-only">(current)</span></a>
            
              
        <li class="nav-item active">
          <a class="nav-link" href="http://127.0.0.1:8000/challan/user_login/">User Login</a> <span class="sr-only">(current)</span></a>
                
        <li class="nav-item active">
          <a class="nav-link" href="http://127.0.0.1:8000/challan/faq/">FAQ's</a> <span class="sr-only">(current)</span></a>

                  

        <li class="nav-item active">
          <a class="nav-link" href="http://127.0.0.1:8000/challan/register">Register</a> <span class="sr-only">(current)</span></a>

                    
          
        <li class="nav-item active">
          <a class="nav-link" href="http://127.0.0.1:8000/challan/rules">Traffic Rules</a> <span class="sr-only">(current)</span></a>


        
                        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
                        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
                      
        
        <li class="nav-item active" style="margin-left: 425px;">
            {% if user.is_authenticated %}
            <div class="user-container">
                <div class="dropdown">
                    <button onclick="toggleDropdown()" class="dropbtn">{{ user.username }}   <i class="fa-solid fa-user"></i></button>
                    <div id="dropdown-content" class="dropdown-content">
                        <a href="{% url 'traffic:police_logout'%}">Logout</a>
                    </div>
                </div>
            </div>
        {% else %}
            <div class="user-container">
                <a href="#" class="login-link">Login</a>
            </div>
        {% endif %}
    </header>

        </li>             
                        
        </li>
        </ul>

    
          
  </nav>

            


<script>
  function toggleDropdown() {
    var dropdownContent = document.getElementById("dropdown-content");
    dropdownContent.classList.toggle("show");
  }
  
  window.onclick = function(event) {
    if (!event.target.matches('.dropbtn')) {
      var dropdowns = document.getElementsByClassName("dropdown-content");
      for (var i = 0; i < dropdowns.length; i++) {
        var openDropdown = dropdowns[i];
        if (openDropdown.classList.contains('show')) {
          openDropdown.classList.remove('show');
        }
      }
    }
  }
  
</script>

</body>
</html>



 
  </body>
  </html>

challan_bkp/challan/traffic/templates/traffic/user_dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  {% load static %}
 
 

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  <style>
    
    body {
      font-family: Arial, sans-serif;
      background-color:#f8f9fa;
      margin: 0;
      padding: 0;
    }

    .header {
      background-color: #333;
      color: #fff;
      padding: 20px;
      text-align: center;
      box-shadow: 0 2px 10px rgba(0, 0, 0, 0.3);
    }

    .header h1 {
      margin: 0;
      font-size: 32px;
      text-transform: uppercase;
      letter-spacing: 2px;
    }

    .header img {
      max-width: 200px;
      margin-top: 10px;
    }

    h3 {
      text-align: center;
      margin-top: 30px;
      color: #333;
    }

    .navbar {
      background-color: #fff;
      padding: 10px;
      text-align: center;
      margin-bottom: 20px;
      box-shadow: 0 4px 10px rgba(0, 0, 0, 0.2);
    }

    .navbar a {
      color: #333;
      text-decoration: none;
      margin: 0 10px;
      font-weight: bold;
      transition: color 0.3s ease;
    }

    .navbar a:hover {
      color: #ff6b6b;
    }
    
  </style>
</head>
  <body>
    {% load static %}
  <div class="header">
  <h1>Telangana Traffic Police</h1>
  
  
</div>
<h3>E Challan Portal</h3>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
   
    <img src="{% static 'traffic/photos/2.png'%}" alt="Logo" style="height: 100px;">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="http://127.0.0.1:8000/challan/home">Home <span class="sr-only">(current)</span></a>

        <li class="nav-item active">
          <a class="nav-link" href="http://127.0.0.1:8000/challan/contact">Contact US</a> <span class="sr-only">(current)</span></a>

        <li class="nav-item active">
          <a class="nav-link" href="http://127.0.0.1:8000/challan/police_login">Police Login</a> <span class="sr-only">(current)</span></a>
            
              
        <li class="nav-item active">
          <a class="nav-link" href="http://127.0.0.1:8000/challan/user_login/">User Login</a> <span class="sr-only">(current)</span></a>
                
        <li class="nav-item active">
          <a class="nav-link" href="http://127.0.0.1:8000/challan/faq/">FAQ's</a> <span class="sr-only">(current)</span></a>

                  

        <li class="nav-item active">
          <a class="nav-link" href="http://127.0.0.1:8000/challan/register">Register</a> <span class="sr-only">(current)</span></a>

                    
          
        <li class="nav-item active">
          <a class="nav-link" href="http://127.0.0.1:8000/challan/rules">Traffic Rules</a> <span class="sr-only">(current)</span></a>


        <li class="nav-item active">
            <a class="nav-link" href="http://127.0.0.1:8000/challan/report">Complain</a> <span class="sr-only">(current)</span></a>

        
                        
                      
        
        <li class="nav-item active" style="margin-left: 300px;">
            {% if user.is_authenticated %}
            <div class="user-container">
                <div class="dropdown">
                    <button onclick="toggleDropdown()" class="dropbtn">{{ user.username }}   <i class="fa-solid fa-user"></i></button>
                    <div id="dropdown-content" class="dropdown-content">
                        <a href="{% url 'traffic:user_logout'%}">Logout</a>
                    </div>
                </div>
            </div>
        {% else %}
            <div class="user-container">
                <a href="#" class="login-link">Login</a>
            </div>
        {% endif %}
    </header>

        </li>             
                        
        </li>
        </ul>

    
          
  </nav>

            


<script>
  function toggleDropdown() {
    var dropdownContent = document.getElementById("dropdown-content");
    dropdownContent.classList.toggle("show");
  }
  
  window.onclick = function(event) {
    if (!event.target.matches('.dropbtn')) {
      var dropdowns = document.getElementsByClassName("dropdown-content");
      for (var i = 0; i < dropdowns.length; i++) {
        var openDropdown = dropdowns[i];
        if (openDropdown.classList.contains('show')) {
          openDropdown.classList.remove('show');
        }
      }
    }
  }
  
</script>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

</body>
</html>



 
  </body>
  </html>